### PR TITLE
Adding support for base types besides floats, ints, and strings

### PR DESCRIPTION
**Pull request by JohnHBrock**
Somewhat related to #17.

### CODE REVIEW

**Comment by carlobaldassi** [comment]
Thanks!

**Comment by c42f** [comment]
This is a cool feature, though per the security concerns in #17, should we really be embedding the julia parser itself even more deeply in the command line argument parsing process?  I fear that once people start using this feature in full generality, it will be impossible to go back to to something simple and secure.  (Unless there's a way to run the parser in a security restricted mode, only allowing parsing of a given type, and no macro expansion, etc?)

**Comment by c42f** [comment]
It would be a shame to get into a situation where accepting command line user input to a script forced me to run a separate external script to sanitize the inputs.

**Comment by JohnHBrock** [comment]
I agree. This PR was meant to restore broken functionality, but this may not be a desirable feature long-term. A better approach, for example, might be to include an optional function property for each argument that can map a string or vector of strings to whatever the desired type is.

**Comment by c42f** [comment]
Ah right.  Has this broken functionality been present since 0.2 though?  If so, I think the ability to parse only simple floats and ints etc would count as a feature by now ;-)  At least we could make use of it to avoid giving too much power which later becomes a liability.

I wonder if it would make sense to have a restricted julia parser mode which only accepted literals or some such.  I'm not sure if this makes sense, but I recall it's been done before in the python world: a restricted subset of syntax for literals which is cheaper and simpler to parse, and without the security gotchas of allowing arbitrary code.

**Pull request merged**
